apiVersion: apps/v1
kind: Deployment
metadata:
  name: ethereal-deployment
  namespace: default
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: ethereal
        image: ${{ secrets.myImageRepo }}
        ports:
        - containerPort: 80


