apiVersion: v1
kind: Service
metadata:
  name: ethereal-service
  namespace: default
  labels:
    app: webapp
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80 # port utilisé par le service
      targetPort: 80 # ports des pods dans le deployment DUDE This Has TO be NGinx Listening Port
      nodePort: 30344 # plage d'ip = [30000,...,32767], toutes les ips seront redirigiées vers celui ci
  selector:
    app: webapp
