apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: etherealsite-rs
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: etheral
        image: ${{ secrets.myImageRepo }} #or your image from docker hub
